### ISSUE TITLE
No module named 'monkey'

### ISSUE THREAD

**Issue by snakecy** [karellen/geventmp#1]
ModuleNotFoundError: No module named 'monkey'

```
from monkey import patch_all
```

**Comment by arcivanov** [comment]
![Huh](https://i.giphy.com/media/glmRyiSI3v5E4/giphy.webp)

https://github.com/karellen/geventmp/blob/master/src/greentest/test_monkey_mp.py#L5

Please post an executable code snippet next time as well.

**Comment by orestis-z** [comment]
I'm guessing it should be `from geventmp.monkey import patch_all`

**Comment by arcivanov** [comment]
well yes, or 
```python
from geventmp import monkey
monkey.patch_all()
```

**Comment by arcivanov** [comment]
Ah, lol I figured out what you're saying. You're talking about README.
Thanks, I'll fix it.
