### ISSUE TITLE
Feature request: New release?

### ISSUE THREAD

**Issue by spchamp** [karellen/geventmp#28]
Could there be a new release in the schedule?

I notice that there have been some changes in the codebase since the most recent public release of geventmp, version 0.0.8. For instance, there is the changeset [8b1c397](https://github.com/karellen/geventmp/commit/8b1c397219e078ef8ec75a64d6b0982e25b08b08) which may have included some updates to the [`geventmp.monkey`](https://github.com/karellen/geventmp/blob/a9ac82a50cf61f22706d2c10fc9d5f7ef71c23b7/src/main/python/geventmp/monkey.py) module. 

If there could be a newer geventmp release available, perhaps it could help for applications in testing for instance?

In arriving at the question, I was using the following updates to the [billiard sources](https://github.com/celery/billiard) for purpose of local tests.

Contents of billiard [`requirements/test.txt`](https://github.com/celery/billiard/blob/f7810403890c7024913595e1a6a15437281ed4a5/requirements/test.txt) locally patched to include dependencies for gevent, geventmp
```
cffi>=1.12.2
gevent>=24.11.1
geventmp>=0.0.8
greenlet>=3.0
pytest>=6.2
psutil>=5.9.0
```

Contents of [billiard `tox.ini`](https://github.com/celery/billiard/blob/f7810403890c7024913595e1a6a15437281ed4a5/tox.ini) locally patched to run tests under patching with gevent and geventmp:
```
[tox]
requires =
    tox-gh-actions
envlist = {3.8,3.9,3.10,3.11,3.12}-unit
skip_missing_interpreters = True

[gh-actions]
python =
    3.8: 3.8-unit
    3.9: 3.9-unit
    3.10: 3.10-unit
    3.11: 3.11-unit
    3.12: 3.12-unit

[testenv]
distribute = True
sitepackages = False
commands = python -m gevent.monkey --module pytest -xv
deps=
    -r{toxinidir}/requirements/test-ci.txt
    -r{toxinidir}/requirements/test.txt
```

This results in an exception during the build. The exception seems to be related to the inline patching for gevent and geventmp, using the  0.0.8 release of geventmp and the latest gevent and greenlet sources.

Of course, the latest geventmp sources can be used via a git-based dependency in the requirements text file, for instance in updating the patch to billiard's [`requirements/test.txt`](https://github.com/celery/billiard/blob/f7810403890c7024913595e1a6a15437281ed4a5/requirements/test.txt) 

```
cffi>=1.12.2
gevent>=24.11.1
git+https://github.com/karellen/geventmp.git
greenlet>=3.0
pytest>=6.2
psutil>=5.9.0
```

The patched tox config can then be applied as normally for billiard,  within the billiard source dir:

```bash
make test
```

Using the latest geventmp sources, the tests all seem to pass under this patched test config. I'm using Python 3.11.9 built with pyenv, on openSUSE LEAP 15.6, amd64 architecture. I'll try to test this also under Windows.

If there was a newer release available for geventmp, of course it would simplify the process of installing the test dependencies in this example.

**Comment by arcivanov** [comment]
Oh crap, I'm so sorry, I thought I released the latest update!
I'll push it out ASAP.

**Comment by arcivanov** [comment]
Released. Sorry for the delay.
