### ISSUE TITLE
Strange behaviors from queues got from a SyncManager

### ISSUE THREAD

**Issue by spl0k** [karellen/geventmp#9]
Hello.

For the sake of readability, let's assume the following imports:
```python
from multiprocessing.connection import Client, Listener
from multiprocessing.managers import SyncManager
```

I'm getting strange behaviors from `Queue`s created by a `SyncManager` when using `gevent` and `geventmp`, but first let me describe a bit the application architecture.
The app is split in two parts: a web app served by `gunicorn` and another independently run process that we'll refer to as the monitor here. This monitor starts both a `Listener` and a `SyncManager`. In the web app, one of the route opens a connection to the monitor with a `Client`, the monitor then asks the `SyncManager` to create a new `Queue` and sends it back to the web app. Once it has retrieved the queue, the web app calls `close()` on the `Client` and uses the queue with the following code:

```python
while True:
    try:
        data = queue.get(timeout=10)
        queue.task_done()

        if data is None:
            break

        yield data
    except Empty:
        yield ":\n"  # Send keep-alives
```

These queues are never reused, every request coming to this endpoint causes a new queue to be created. The code above is the only one on the web side to use the queues and this is the only place where we call `get()` or `task_done()` on the queues. Only the monitor or its child processes (because it also spawns other processes, but I doubt this is relevant) are calling `put()` on the queues.

This worked well when we weren't using `gevent` (`gunicorn` with `sync` workers, if you put aside the inherent scalability issue of serving never ending requests with `sync` workers). With `gevent` alone (`gunicorn` started with `gevent` workers, no `geventmp` installed) we couldn't get past the `Client` initial connection, so we tried with `geventmp`. This solved the `Client` issue and we could get and use the queue, but some other issues started to appear when several (HTTP) clients tried to connect to this route.

The first issue is the `queue.get()` sometimes returning `None` for no reason, when no `None` was `put()` in the first place. Before every `put()` we made sure than no `None` was sent by `assert`-ing it, but it kept happening nonetheless without any assert failing.

Another issue is that we sometimes get a `ValueError` exception thrown about `task_done()` being called too many times, with this traceback:
```
Traceback (most recent call last):
  File "/.../sse.py", line 66, in event_source
    queue.task_done()
  File "<string>", line 2, in task_done
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
ValueError: task_done() called too many times
```
Since the code above is the only one calling this method there is no reason for this this exception for being thrown. But what is even more strange is that the exception sometimes appear on the `get()` call:
```
Traceback (most recent call last):
  File "/.../sse.py", line 65, in event_source
    data = queue.get(timeout=10)
  File "<string>", line 2, in get
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
ValueError: task_done() called too many times
```

None of this happened when we used the `sync` workers. At first only the web part was using `gevent`, not the monitor. But patching the monitor with `gevent.monkey.patch_all()` (before any other import, obviously) results in the same strange behavior.
Any insight as to why this is happening?

This is using the following:
- Debian 10.11
- Python 3.7.3
- Flask 1.1.1
- gunicorn 20.1.0
- gevent 21.12.0
- geventmp 0.0.1
- werkzeug 0.16.1

**Comment by arcivanov** [comment]
There may have been changes with the latest gevent. Let me see if I can run some tests.

**Comment by arcivanov** [comment]
@spl0k 
So there are many issues here, specifically GUnicorn is non-trivial. Have you tried using GUnicorn with async gevent workers?

https://docs.gunicorn.org/en/latest/install.html?highlight=gevent#async-workers

**Comment by spl0k** [comment]
The problems listed above appear when using gunicorn with `gevent` workers.
gunicorn with `sync` workers "works" (but again, this isn't a viable solution); and I just tested with `eventlet` workers, there doesn't seem to be a problem either. So I'd say it's coming from either `gevent` or `geventmp` (since we're dealing with `multiprocessing`-based IPCs here)

As per your previous comment I also tried with older versions of `gevent` and `greenlet` (versions that were released when `geventmp` 0.0.1 was released): I'm getting the same issues.

**Comment by arcivanov** [comment]
Understood, thanks!

**Comment by arcivanov** [comment]
@spl0k what kind of Queue are we talking about? `mp.Queue` or `queue.Queue`?

**Comment by spl0k** [comment]
[`mp.managers.SyncManager().Queue`](https://github.com/python/cpython/blob/3.7/Lib/multiprocessing/managers.py#L1206), so a `queue.Queue` behind a `mp.managers.AutoProxy`.

**Comment by arcivanov** [comment]
@spl0k to give you an update, I think I just found the problem.

Since there are three processes involved (gunicorn, monitor and a SyncManager Server) it was really hard to debug, but I think I just saw something that I shouldn't have.

**Comment by arcivanov** [comment]
Judging by what I'm seeing right now, there is a connection confusion between several green threads. So the reason you're getting `task_done() called too many times` is because when connections get confused `task_done` from several _threads_ may end up in a single connection. I'm still trying to figure out how is that at all possible.

**Comment by arcivanov** [comment]
Another thing you should also be seeing is unexpected `None` arriving.

**Comment by arcivanov** [comment]
Issue found and fixed - it was a problem with patching `threading.local` in MP.

**Comment by arcivanov** [comment]
@spl0k Please try the following version and let me know if the issue you have is resolved: https://pypi.org/project/geventmp/0.0.2.dev20220118144459/

**Comment by arcivanov** [comment]
Version 0.0.2 of https://github.com/karellen/geventmp released with multiple fixes and extensive testing on Linux.

**Comment by arcivanov** [comment]
@spl0k has the issue been resolved?

**Comment by spl0k** [comment]
Sorry, I hadn't had the time to test it yet. Hopefully I'll be able to give you an answer today.

**Comment by spl0k** [comment]
Hello again.
Version 0.0.2 looks like it solved the issue :) Thank you for your time.

**Comment by arcivanov** [comment]
Thanks for the bug report!
